[package]
name = "optimizers"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
indicatif = "0.18.3"
once_cell = "1.21.3"
plotters = "0.3.7"
rand = "0.9.2"
rand_distr = "0.5.1"
rayon = "1.11.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
